### ISSUE TITLE
Recommendation to rewrite content in Markdown format

### ISSUE THREAD

**Issue by rjvitorino** [NeeravSood/MLpedia#1]
## Description:

I'd like to suggest an improvement to enhance the readability and accessibility of the content. Currently, the repository's content appears to be in a non-Markdown format, which may limit its flexibility and readability. To address this, I recommend rewriting the content in Markdown format.

## Objectives:

* Rewrite existing content in Markdown format for improved readability and flexibility.
* Ensure consistency and clarity in content presentation.
* Enhance the user experience by implementing Markdown features such as headers, lists, and formatting styles.

## Proposed Changes:

* **Content Conversion**: Convert all existing content within the repository to Markdown format. This will allow for easier editing and formatting, as well as better compatibility with various platforms and tools.
* **Markdown Formatting**: Adhere to best practices for Markdown formatting to ensure consistency and readability throughout the repository. This includes using proper headers, lists, and formatting styles, as well as incorporating images and code snippets where necessary.

## Benefits:

* Improved readability and flexibility with Markdown format.
* Enhanced compatibility with various platforms and tools.
* Consistency and clarity in content presentation.

## Assigned To:
*  Repository Owner @NeeravSood

**Comment by NeeravSood** [comment]
Dear Ricardo

Thank you for your feedback. I have changed a few things and added
the Markdown. Please let me know if you have any more suggestions. I will
be happy to incorporate the same.

Regards,

*Neerav Sood*

**Comment by rjvitorino** [comment]
> Dear Ricardo Thank you for your feedback. I have changed a few things and added the Markdown. Please let me know if you have any more suggestions. I will be happy to incorporate the same. Regards, *Neerav Sood*

Thanks @NeeravSood I've done some minor contributions, hope these help!
